Added a command example.
Rollczi/LiteCommands pull request #100
Opened 2022-07-18 20:03 UTC by Skyy0x

An example of a command to learn about use Joiner.

2022-07-21 16:13 UTC, Rollczi requested changes

2022-07-21 16:13 UTC, Rollczi commented on examples/bukkit/src/main/java/dev/rollczi/example/bukkit/FuckOffCommand.java
> +@Section(route = "fuckoff", aliases = "wypierdalaj")
kick

2022-07-21 16:13 UTC, Rollczi commented on examples/bukkit/src/main/java/dev/rollczi/example/bukkit/FuckOffCommand.java
> +@Permission("dev.rollczi.fuckoff")
dev.rollczi.kick

2022-07-21 16:13 UTC, Rollczi commented on examples/bukkit/src/main/java/dev/rollczi/example/bukkit/FuckOffCommand.java
> +public class FuckOffCommand {
KickCommand

2022-07-21 16:13 UTC, Rollczi commented on examples/bukkit/src/main/java/dev/rollczi/example/bukkit/FuckOffCommand.java
> +    public void banPlayer(final Player sender, @Arg @Name("target") final Player target, @Joiner final String reason){
banPlayer -> kickPlayer

2022-07-21 16:13 UTC, Rollczi commented on examples/bukkit/src/main/java/dev/rollczi/example/bukkit/FuckOffCommand.java
> +    public void banPlayer(final Player sender, @Arg @Name("target") final Player target, @Joiner final String reason){
```suggestion
    void kickPlayer(@Arg @Name("target") Player target, @Joiner String reason) {

```

2022-07-21 16:13 UTC, Rollczi commented on examples/bukkit/src/main/java/dev/rollczi/example/bukkit/FuckOffCommand.java
> +        Bukkit.broadcastMessage(ChatUtil.color("&cPlayer &7" + target.getName() + " &cgot fucked up!"));
Use Server#broadcastMessage

2022-07-21 18:28 UTC, Skyy0x reviewed
changes

2022-07-25 13:04 UTC, Rollczi requested changes

2022-07-25 13:04 UTC, Rollczi commented on examples/bukkit/src/main/java/dev/rollczi/example/bukkit/FuckOffCommand.java
> +        Bukkit.broadcastMessage(ChatUtil.color("&cPlayer &7" + target.getName() + " &chas been kicked!"));
Użyj Server#broadcastMessage

2022-07-25 13:04 UTC, Rollczi commented on examples/bukkit/src/main/java/dev/rollczi/example/bukkit/FuckOffCommand.java
> +    public void kickPlayer(Player sender, @Arg @Name("target") Player target, @Joiner String reason){
`( {`

2022-07-25 13:26 UTC, Rollczi approved these changes

2022-07-25 13:38 UTC, vLuckyyy approved these changes

2022-07-25 13:44 UTC, Rollczi approved these changes

2022-07-25 13:45 UTC, merged