Add BigInteger and BigDecimal argument support
Rollczi/LiteCommands pull request #255
Opened 2023-10-17 21:42 UTC by BlackBaroness

I also extended `AssertSuggest`'s contract by adding `assertNotEmpty` and `assertCorrect` functions. `assertNotEmpty` allows us to test every suggestion and print exact failing suggestion in case of assertion fails. Now, because of lack of such function, we can't understand which suggestion is broken.

2023-10-18 15:23 UTC, Rollczi requested changes
Resolve merge conflicts

2023-10-18 15:23 UTC, Rollczi commented on litecommands-annotations/test/dev/rollczi/litecommands/annotations/argument/resolver/standard/BigDecimalArgumentTest.java
> +        final BigDecimal testBigInteger = BigDecimal.ZERO
```suggestion
        BigDecimal testBigInteger = BigDecimal.ZERO
```

2023-10-19 10:53 UTC, BlackBaroness commented
Done

2023-10-19 17:12 UTC, merged

2023-10-19 17:12 UTC, Rollczi commented
Thanks