Suggestion tooltip
Rollczi/LiteCommands pull request #461
Opened 2024-10-24 11:21 UTC by huanmeng-qwq

The suggested content includes tooltip text

2024-10-24 11:28 UTC, huanmeng-qwq commented
![img_v3_02fv_4e928ddb-af49-4c3b-a620-67d7e7c5f8dg](https://github.com/user-attachments/assets/d9506c47-e962-4d61-a796-8850bd9c5427)

2024-10-24 13:07 UTC, huanmeng-qwq commented
Ok.

2024-10-25 05:40 UTC, huanmeng-qwq commented
@Rollczi 
Hi, can you review this PR?

2024-10-25 22:21 UTC, Rollczi commented
I will review that on Monday

2024-10-28 12:28 UTC, Rollczi requested changes

2024-10-28 12:28 UTC, Rollczi commented on litecommands-core/src/dev/rollczi/litecommands/suggestion/Completion.java
> +public class Completion {
I think this class is useless and represents the same thing as Suggestion.

2024-10-28 12:28 UTC, Rollczi commented on litecommands-unit/src/dev/rollczi/litecommands/unit/AssertSuggest.java
> +    public AssertSuggest assertSuggest(String[] suggestions, String... tooltips) {
If we want to assert suggestions with tooltip, then I think we should create method with varargs Suggestion... parameter

2024-10-28 14:27 UTC, huanmeng-qwq commented
I have completed the modifications. However, should we use tooltips on all platforms? Currently, I only apply tooltips to parameters registered on the fabric platform.

2024-10-28 14:33 UTC, Rollczi commented on litecommands-core/src/dev/rollczi/litecommands/suggestion/SuggestionResult.java
> +    public static SuggestionResult tooltip(Iterable<String> suggestions, Iterable<String> tooltips) {
remove this method

2024-10-28 14:34 UTC, Rollczi commented on litecommands-core/src/dev/rollczi/litecommands/suggestion/SuggestionResult.java
> +    public static SuggestionResultCollector tooltipCollector() {
such tooltips don't make much sense

2024-10-28 14:34 UTC, Rollczi commented on litecommands-core/src/dev/rollczi/litecommands/suggestion/SuggestionResultCollector.java
> +    public SuggestionResultCollector(boolean copyTooltip) {
rollback

2024-10-28 14:36 UTC, Rollczi commented on litecommands-unit/src/dev/rollczi/litecommands/unit/AssertSuggest.java
> +    public AssertSuggest assertTooltip(Collection<String> tooltips) {
> If we want to assert suggestions with tooltip, then I think we should create method with varargs Suggestion... parameter

```suggestion
    public AssertSuggest assertSuggest(Suggestion... suggestions) {
```

2024-10-28 14:37 UTC, Rollczi commented on litecommands-bukkit/src/dev/rollczi/litecommands/bukkit/TabCompleteProtocolLibAsync.java
> +        } catch (LiteCommandsReflectException exception) {
please don't change the code style for try catch

2024-10-28 14:43 UTC, Rollczi commented
> I have completed the modifications. However, should we use tooltips on all platforms? Currently, I only apply tooltips to parameters registered on the fabric platform.

It would be useful to support all platforms that provide such possibilities (I guess e.g. JDA doesn't allow it)

2024-10-29 14:29 UTC, huanmeng-qwq commented
@Rollczi Please review

2024-10-29 23:01 UTC, Rollczi commented
Hi @huanmeng-qwq,
I added collector and copying of tooltip to new suggestions. Now tooltip is not null.

One important think: we need to think about tooltips like as experimental and unstable feature becasue it is only related to minecraft's domain and we need also to think about supporting adventure API. Thats means in the future I will need to change this API to support also components/json.

2024-10-30 01:24 UTC, huanmeng-qwq commented
Yes, plain text only is currently supported, and future versions should support the use of the adventure API or the component api available on minecraft Vanilla on some platforms



---Original---
From: "Norbert ***@***.***&gt;
Date: Wed, Oct 30, 2024 07:01 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Rollczi/LiteCommands] Suggestion tooltip (PR #461)




 
Hi @huanmeng-qwq,
 I added collector and copying of tooltip to new suggestions. Now tooltip is not null.
 
One important think: we need to think about tooltips like as experimental and unstable feature becasue it is only related to minecraft's domain and we need also to think about supporting adventure API. Thats means in the future I will need to change this API to support also components/json.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2024-10-30 11:39 UTC, Rollczi approved these changes

2024-10-31 08:53 UTC, huanmeng-qwq commented
When can we merge this PR? or how should I use this snapshot version? @Rollczi

2024-10-31 18:14 UTC, Rollczi commented
If you think all is done then we can merge it

2024-11-02 01:22 UTC, huanmeng-qwq commented
> If you think all is done then we can merge it如果你认为一切都完成了那么我们可以合并它

Yes, it can be merged now

2024-11-02 10:47 UTC, merged